server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.109.130
      database: spitdb
  redis:
    host: 192.168.109.130
jwt:
  config:
    key: tensquare
    ttl: 3600000